Build: test.cpp poisson_disk_sample.hpp main.cpp ../../Thread/nearest_point/nearest_point/near_point.hpp
		g++ -Ofast test.cpp -march=native -std=c++20 -o test -Wall -Wextra
		g++ main.cpp -Ofast -march=native -std=c++20 -o main -Wall -Wextra
clean:
		rm test main
		
