all: yykhf unyykhf
.PHONY: all
yykhf: yykhf.cpp
		g++ -O3 yykhf.cpp -o yykhf -std=c++17 -Wall
unyykhf: unyykhf.cpp
		g++ -O3 unyykhf.cpp -o unyykhf -std=c++17 -Wall
clean : 
	   rm yykhf unyykhf
move	:
			cp yykhf unyykhf /usr/bin/
